package model;

public enum CellType {
    WALL,
    WALL_NO_COLLISION,
    EMPTY,
    SPAWNING_POOL,
    POINT,
    PACMAN,
    GHOST,
    GHOST_HARMLESS,
    POWERUP_SLOW_GHOSTS,
    POWERUP_FREEZE,
    POWERUP_EXTRA_LIFE,
    POWERUP_HARMLESS_GHOSTS,
    POWERUP_SPEED_UP
}
